services:
  typeshed-serializer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ../src:/sonar-python/python-frontend/src
      - ./checksum:/sonar-python/python-frontend/typeshed_serializer/checksum
    user: ${UID}:${GID}