services:
  typeshed-serializer:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    # mount the generated typeshed proto files destination directory and checksum file to the container
    volumes:
      - ../../src:/sonar-python/python-frontend/src
      - ../checksum:/sonar-python/python-frontend/typeshed_serializer/checksum
    # Pass current host machine user ids to keep the files ownership
    user: ${USER_ID}:${GROUP_ID}
